<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-26T12:03:34 IST" name="Default suite" finished-at="2025-04-26T12:04:05 IST" duration-ms="30562">
    <groups>
    </groups>
    <test started-at="2025-04-26T12:03:34 IST" name="Default test" finished-at="2025-04-26T12:04:05 IST" duration-ms="30562">
      <class name="MyTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:MyTest@147e2ae7]" started-at="2025-04-26T12:03:34 IST" name="setup" finished-at="2025-04-26T12:03:39 IST" duration-ms="4657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testFormSubmission()[pri:0, instance:MyTest@147e2ae7]" started-at="2025-04-26T12:03:39 IST" name="testFormSubmission" finished-at="2025-04-26T12:04:05 IST" duration-ms="25426" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Element could not be found even after self-healing.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Element could not be found even after self-healing.
at MyTest.findElementWithSelfHealing(MyTest.java:62)
at MyTest.testFormSubmission(MyTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFormSubmission -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyTest@147e2ae7]" started-at="2025-04-26T12:04:05 IST" name="tearDown" finished-at="2025-04-26T12:04:05 IST" duration-ms="360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
